<?php

namespace AppBundle\Repository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends \Doctrine\ORM\EntityRepository
{

    public function getRevenue()
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT SUM(c.price)
        FROM AppBundle:Contract c'
        );

        // returns an array of Product objects
        return $query->getResult();
    }

    public function getRevenue_On_Range($date_in,$date_out)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(

            'SELECT SUM(c.price)
        FROM AppBundle:Contract c 
    WHERE c.createdOn BETWEEN  :date_in AND  :date_out'
        )
            ->setParameter('date_in', $date_in)
            ->setParameter('date_out', $date_out);

        // returns an array of Product objects
        return $query->getResult();


    }
}
